name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app-release.jks

    - name: Build release artifacts
      run: ./gradlew assembleRelease bundleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: dnd-toggle-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: dnd-toggle-aab
        path: app/build/outputs/bundle/release/app-release.aab

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: dnd-toggle-apk

    - name: Download AAB artifact
      uses: actions/download-artifact@v4
      with:
        name: dnd-toggle-aab

    - name: Get Version Name
      id: get_version
      run: |
        VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk -F'"' '{print $2}')
        echo "::set-output name=version_name::$VERSION_NAME"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version_name }}
        release_name: Release v${{ steps.get_version.outputs.version_name }}
        draft: false
        prerelease: false

    - name: Upload Release AAB
      id: upload-release-aab
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app-release.aab
        asset_name: dnd-toggle-v${{ steps.get_version.outputs.version_name }}.aab
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Release APK
      id: upload-release-apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app-release.apk
        asset_name: dnd-toggle-v${{ steps.get_version.outputs.version_name }}.apk
        asset_content_type: application/vnd.android.package-archive
